%%{init: {'themeVariables': {'nodeTextColor':'#000'}}}%%
flowchart TD
    classDef data fill:#e6f3ff,stroke:#66b3ff,stroke-width:2px
    classDef op fill:#ffe6e6,stroke:#ff6666,stroke-width:2px,shape:round-rect

    data14["SCRNA _x458+18157 gene expressions"]:::data
    op9["Splitter"]:::op
    data15["SCRNA gene expressions _x458"]:::data
    data16["SCRNA gene expressions _x18157"]:::data
    data14 --> op9 --> data15 & data16
    data17["Gene names 458"]:::data
    op10["Extract Names"]:::op
    data15 --> op10 --> data17
