%%{init: {'themeVariables': {'nodeTextColor':'#000'}}}%%
flowchart TD
    classDef data fill:#e6f3ff,stroke:#66b3ff,stroke-width:2px
    classDef op fill:#ffe6e6,stroke:#ff6666,stroke-width:2px,shape:round-rect

    data4["UC9_I feature PCs N x 44"]:::data
    data17["Gene names 458"]:::data
    data6["UC9_I gene expressions N x 460"]:::data
    data6 & data17--> op4["Filter to Names"]:::op
    op4 --> data7["UC9_I gene expressions N x 458"]:::data
    data7 --> op5["PCAFitTransform"]:::op
    op5 --> data8["UC9_I Gene PCs N x 6"]:::data
    op5 --> data9["UC9_I Basis(458 genes)"]:::data

    data4 & data8 --> op6["RidgeFitTransform"]:::op
    op6 --> data10["UC9_I Ridge weights: Feature PCs -> Gene PCS"]:::data
    op6 --> data11["UC9_I Predicted Gene PCS"]:::data
    data11 --> op8["Metrics"]:::op
    op8 --> data12["UC9_I Gene PCs MSE"]:::data
    op8 --> data13["UC9_I Gene PCs Spearman"]:::data
    data8 --> op8
