%%{init: {'themeVariables': {'nodeTextColor':'#000'}}}%%
flowchart TD
    classDef data fill:#e6f3ff,stroke:#66b3ff,stroke-width:2px
    classDef op fill:#ffe6e6,stroke:#667aff,stroke-width:2px,shape:round-rect
    classDef inputData fill:#e6f3ff,stroke:#00AA00,stroke-width:2px
    classDef outputData fill:#e6f3ff,stroke:#FF00FF,stroke-width:2px
    classDef outputMetric fill:#e6f3ff,stroke:#FFFF00,stroke-width:2px

    data5["UC9_I Basis(feature)"]:::inputData  
    data10["UC9_I Ridge weights: Feature PCs -> Gene PCS"]:::inputData
    data19["SCRNA 18157 Basis"]:::inputData
    data22["SCRNA 18157 Ridge weights: 458 Gene PCS -> 18157 Gene PCS"]:::inputData
    data30["CellType features _x1024"]:::inputData 
    data40["CellType 18615 genes"]:::outputData  

    op21["PCATransform"]:::op
    op23["RidgeTransform"]:::op
    op25["RidgeTransform"]:::op
    op27["PCAInverseTransform"]:::op
    op29["Concatenate"]:::op

    data30 & data5 --> op21
    op21 --> data32["CellType feature PCs _x44"]:::data
    data32 & data10 --> op23 --> data34["CellType 458 gene PCs _x6"]:::data
    data34 & data22 --> op25 --> data36["CellType 18157 predicted gene PCs"]:::data
    data36 & data19 --> op27 --> data38["CellType 18157 predicted genes"]:::data
    data42["CellType 458 genes"]:::inputData
    data42 & data38 --> op29 --> data40
