%%{init: {'themeVariables': {'nodeTextColor':'#000'}}}%%
flowchart TD
    classDef data fill:#e6f3ff,stroke:#66b3ff,stroke-width:2px
    classDef op fill:#ffe6e6,stroke:#667aff,stroke-width:2px,shape:round-rect
    classDef inputData fill:#e6f3ff,stroke:#00AA00,stroke-width:2px
    classDef outputData fill:#e6f3ff,stroke:#FF00FF,stroke-width:2px
    classDef outputMetric fill:#e6f3ff,stroke:#FFFF00,stroke-width:2px

    data2["Chips Nx32x32x3"]:::inputData
    data2 --> op2["Resnet50"]:::op
    op2 --> data3["Features N x 1024"]:::outputData
    op3aa["Visualization"]:::op
    data3aa["Feature density"]:::outputMetric
    data3 --> op3aa --> data3aa