%%{init: {'themeVariables': {'nodeTextColor':'#000'}}}%%
flowchart TD
    classDef data fill:#e6f3ff,stroke:#66b3ff,stroke-width:2px
    classDef op fill:#ffe6e6,stroke:#667aff,stroke-width:2px,shape:round-rect
    classDef inputData fill:#e6f3ff,stroke:#00AA00,stroke-width:2px
    classDef outputData fill:#e6f3ff,stroke:#FF00FF,stroke-width:2px
    classDef outputMetric fill:#e6f3ff,stroke:#FFFF00,stroke-width:2px

    data3["Array N x M"]:::inputData
    data3 --> op3["PCAFit"]:::op
    data4["Data N x K, K <= M"]:::outputData
    data5["Full Basis M x M"]:::outputData
    data6["Eigenvalues"]:::outputData
    data7["Cumulative explained variance"]:::outputData
    op3 --> data5 & data6
    op7["Cumulative sum"]:::op
    data6 --> op7 --> data7
    op4["Cumulative Variance Goal"]:::outputMetric
    op5["Knee method"]:::outputMetric
    op6["Kaiser metric"]:::outputMetric
    data7 --> op4
    data6 --> op6
    data6 --> op5
    op8["max(2,min(K_cumvar,K_knee,K_kaiser))]"]:::op
    op4 & op5 & op6 --> op8
    data9["K"]:::outputData
    op8 --> data9:::outputData
    op9["Trim basis"]:::op
    data10["Basis M x K"]:::outputData
    data5  & data9--> op9 --> data10
    op11["PCA transform"]:::op
    data10 & data3 --> op11 --> data4
