%%{init: {'themeVariables': {'nodeTextColor':'#000'}}}%%
flowchart TD
    classDef data fill:#e6f3ff,stroke:#66b3ff,stroke-width:2px
    classDef op fill:#ffe6e6,stroke:#667aff,stroke-width:2px,shape:round-rect
    classDef inputData fill:#e6f3ff,stroke:#00AA00,stroke-width:2px
    classDef outputData fill:#e6f3ff,stroke:#FF00FF,stroke-width:2px
    classDef outputMetric fill:#e6f3ff,stroke:#FFFF00,stroke-width:2px

    data3["Array N x M"]:::inputData
    data3 --> op3["PCAFitTransform"]:::op
    op3 --> data4["Data N x K, K <= M"]:::outputData
    op3 --> data5["Basis"]:::outputData
    op3aa["Visualization"]:::op
    data3aa["Data density"]:::outputMetric
    data3 --> op3aa --> data3aa
    op3a["Metrics"]:::op
    op3b["Visualization"]:::op
    data3a["MSE"]:::outputMetric
    data3b["% Variance Explained"]:::outputMetric
    data4c["#PCs needed for MSE <= 0.16"]:::outputMetric
    data4 --> op3a --> data3b & data3a
    data4 --> op3b --> data4c