%%{init: {'themeVariables': {'nodeTextColor':'#000'}}}%%
flowchart TD
    classDef data fill:#e6f3ff,stroke:#66b3ff,stroke-width:2px
    classDef op fill:#ffe6e6,stroke:#667aff,stroke-width:2px,shape:round-rect
    classDef inputData fill:#e6f3ff,stroke:#00AA00,stroke-width:2px
    classDef outputData fill:#e6f3ff,stroke:#FF00FF,stroke-width:2px
    classDef outputMetric fill:#e6f3ff,stroke:#FFFF00,stroke-width:2px

    data4["Source N x M1"]:::inputData
    data8["Target N x M2"]:::inputData
    data4 & data8 --> op6["RidgeFitTransform"]:::op
    op6 --> data10["Ridge weights: Source -> Target"]:::outputData
    op6 --> data11["Predicted Target"]:::data
    data11 --> op8["Metrics"]:::op
    op8 --> data12["Target vs Prediction MSE"]:::outputMetric
    op8 --> data13["Target vs Prediction Spearman Rank Correlation"]:::outputMetric
    data8 --> op8
