%%{init: {'themeVariables': {'nodeTextColor':'#000'}}}%%
flowchart TD
    classDef data fill:#e6f3ff,stroke:#66b3ff,stroke-width:2px
    classDef op fill:#ffe6e6,stroke:#667aff,stroke-width:2px,shape:round-rect
    classDef inputData fill:#e6f3ff,stroke:#00AA00,stroke-width:2px
    classDef outputData fill:#e6f3ff,stroke:#FF00FF,stroke-width:2px
    classDef outputMetric fill:#e6f3ff,stroke:#FFFF00,stroke-width:2px

    data25["UC9_I tif"]:::inputData
    data26["UC9_I dysplaysia mask"]:::data
    data27["UC9_I_non-dysplaysia mask"]:::data
    op15["tif field"]:::op
    op16["tif field"]:::op
    data25 --> op15 --> data26
    data25 --> op16 --> data27
    op17["Chipper (specific centroids)"]:::op
    op18["Chipper (specific centroids)"]:::op
    data28["Dysplasia chips: 32x32x3"]:::data
    data29["Non-dysplasia chips: 32x32x3"]:::data
    data25 & data26 --> op17 --> data28
    data25 & data27 --> op18 --> data29
    op19["Resnet50"]:::op
    op20["Resnet50"]:::op
    data28 --> op19
    data29 --> op20
    data30["Dysplasia features _x1024"]:::outputData
    op19 --> data30
    data31["Non-dysplasia features _x1024"]:::outputData
    op20 --> data31
