project_name: broad-3-catskills
description: Integrated pipeline for spatial transcriptomics analysis combining DeepSpot and Tarandros approaches
version: 1.0.0

# Data paths
data_path: data/UC9_I.zarr
region_annotations: input/raw/region_annotations.csv
output_dir: output

# Small dataset parameters
quality_threshold: 0.7
n_samples_per_region: 50
n_dummy_regions: 5
val_test_size: 0.3
seed: 42

# Feature extraction parameters
patch_size: 64
feature_dim: 512
n_subspots: 4
n_neighbors: 6

# Model parameters
phi_dim: 256
embedding_dim: 512
n_heads: 4
dropout: 0.3
use_gene_graph: true

# Training parameters
learning_rate: 0.0005
weight_decay: 0.0001
loss_weight_spearman: 0.7
loss_weight_mse: 0.3
batch_size: 32
max_epochs: 100
patience: 10

# W&B parameters
wandb_project: spatial-transcriptomics
