batch_size: 16
data_path: data/UC9_I.zarr
description: Integrated pipeline for spatial transcriptomics analysis combining DeepSpot
  and Tarandros approaches
dropout: 0.3
embedding_dim: 512
feature_dim: 512
learning_rate: 0.0005
loss_weight_mse: 0.3
loss_weight_spearman: 0.7
max_epochs: 100
n_dummy_regions: 5
n_heads: 4
n_neighbors: 6
n_samples_per_region: 50
n_subspots: 4
output_dir: output/small_dataset
patch_size: 64
patience: 10
phi_dim: 256
project_name: broad-3-catskills
quality_threshold: 0.7
region_annotations: input/raw/region_annotations.csv
seed: 42
small_dataset: true
use_gene_graph: true
val_test_size: 0.3
version: 1.0.0
wandb_project: spatial-transcriptomics
weight_decay: 0.0001
