#!/usr/bin/env python3
"""
Configuration file for synthetic dataset generation.
This file contains parameters for creating synthetic datasets with
well-defined statistical properties for model validation.
"""

# Output directory
output_dir: output
data_path: output/data/synthetic_dataset

# Synthetic dataset parameters
n_cells: 2000
n_genes: 200
n_regions: 5
region_type: circular
space_size: 1000
n_gene_modules: 10
min_module_size: 5
max_module_size: 20
base_expression: 5.0
expression_scale: 2.0
noise_level: 0.2
spatial_effect_strength: 0.5
nb_dispersion: 0.1
quality_noise: 0.1
val_test_size: 0.3

# Model parameters
model_type: mlp
hidden_layers: [512, 256]
dropout: 0.2
learning_rate: 0.001
batch_size: 32
epochs: 100

# Wandb logging
wandb_project: spatial-transcriptomics
